module SCC2020Tool

export write_complex_scc2020

"""
    write_complex_scc2020(filename_or_io, boundary_matrices, grades; kwargs...)

Writes a chain complex of graded persistence modules in the `scc2020` file format by M. Lesnick and M. Kerber.

A chain complex

```
C₁ → C₂ → C₃ → …
```

is represented by a list of boundary matrices `M₁, M₂, M₃, …` and grades `g₁, g₂, …`, where `Mᵢ`
is the boundary map `Cᵢ → Cᵢ₋₁` and `gᵢ` is a list of grades for the generators of `Cᵢ`.

# Arguments
- `filename_or_io::String` or `IO`: The output file name or an IO stream.
- `boundary_matrices`: The list of boundary matrices.
- `grades`: The list of grades for the generators of each chain group.
- `op_params`: (optional) A list of parameter indices to reverse. Default is `Int[]`.
- `n_params`: (optional) The number of parameters. Default is inferred from the first element in `grades[1]`.
- `field`: (optional) The field. Default is `"GF(2)"`.
"""
function write_complex_scc2020(filename::String, boundary_matrices, grades; op_params=Int[], n_params=length(grades[1][1]), field="GF(2)")
    open(filename) do f
        write_complex_scc2020(f, boundary_matrices, grades; op_params=op_params, n_params=n_params, field=field)
    end
end

function write_complex_scc2020(io::IO, boundary_matrices, grades; op_params=Int[], n_params=length(grades[1][1]), field="GF(2)")
    println(io, "# SCC2020 file format")
    println(io, "# Generated by SCC2020Tool.jl")

    println(io, "scc2020") # First line
    println(io, "$(n_params)",) # Second line: number of parameters

    # third line: grades, starting with highest dimension
    n_simplices_top_to_bot = reverse(length.(grades))
    println(io, join(n_simplices_top_to_bot, " "))

    # optional reverse line
    if !isempty(op_params)
        println(io, "--reverse ", join(op_params, " "))
    end

    # field line
    if field != ""
        println(io, "--field ", field)
    end

    # blocks
    for (matrix, col_grades) in zip(Iterators.reverse(boundary_matrices), Iterators.reverse(grades))
        println(io, "# block start:")
        write_scc2020_block(io, matrix, col_grades; write_coefficients=field != "GF(2)")
    end
    println(io, "# final block:")
    write_scc2020_last_block(io, grades[1])
end

function write_scc2020_block(io, matrix, col_grades; write_coefficients=true)
    for (grade, col) in zip(col_grades, eachcol(matrix))
        print(io, join(grade, " "))
        print(" ;")
        for i in findall(!=(0), col)
            print(io, " $i")
            if write_coefficients
                print(io, ":$(col[i])")
            end
        end
        println(io)
    end
end

function write_scc2020_last_block(io, grades)
    for grade in grades
        print(io, join(grade, " "))
        println(" ;")
    end
end

end
